config/routes.rb
Elephant::Application.routes.draw do
  resources :old_docs

  resources :searches, :only => [:new, :create, :index]

  match 'email_tests/jason'
  resources :email_tests

  match 'cash_books/create_ajax' #=> 'cash_books#create_ajax'
  match 'cash_books/clear'
  resources :cash_books

  match 'authentication/sign_on'
  match 'authentication/login'
  match 'authentication/logout'
  match 'authenticated' => 'authenticated#index'

  match 'documents/preview/:id' => 'documents#preview'
  match 'documents/address_choice/:id' => 'documents#address_choice'
  match 'documents/ajax_choice_linked'
  match 'documents/ajax_destroy_linked'
  match 'documents/ajax_create_linked'
  match 'documents/select_address/:id' => 'documents#select_address'
  match 'documents/destroy_ajax_document'
  resources :documents
  
  resources :document_aliases, :only => [:new, :create]

  match 'emails/unseen_emails' => 'emails#unseen_emails'
  match 'emails/seen/:id' => 'emails#seen'
  match 'emails/destroy_ajax_document'
  resources :emails

  match 'talks/destroy_ajax_document'
  resources :talks
  resources :phone_calls, :controller => :talks
  resources :visits, :controller => :talks

  match 'papers/file/:id(.:format)' => 'papers#file'
  match 'papers/unfile/:id(.:format)' => 'papers#unfile'
  match '/papers/open_invoices'
  match 'papers/change_scale/:id' => 'papers#change_scale'
  match 'papers/ajax_set_state_paid'
  match 'papers/dun_from_invoice'
  match 'papers/invoice_from_offer'
  match 'papers/invoices_from_offer'
  match 'papers/destroy_ajax_document/:id(.:format)' => 'papers#destroy_ajax_document'
  match 'papers/send_by_email/:id' => 'papers#send_by_email'
  resources :papers
  resources :paper_file, :only => [:index, :create, :destroy]

  match 'external_papers/destroy_ajax_document/:id(.:format)' => 'external_papers#destroy_ajax_document'
  match 'external_papers/send_by_email/:id' => 'external_papers#send_by_email'
  resources :external_papers

  match 'contents/new_ajax_content'
  match 'contents/create_ajax_pagebreak'
  match 'contents/create_pagebreak'
  match 'contents/create_ajax_content'
  match 'contents/edit_ajax_content'
  match 'contents/update_ajax_content'
  match 'contents/destroy_ajax_content'
  match 'contents/change_scale/:id' => 'contents#change_scale'
  match 'contents/order_contents'
  match 'contents/order_items'
  match 'contents/cancel_ajax'
  match 'contents/reset_signer'
  resources :contents

  match 'rblock_lines/abschlag'
  match 'rblock_lines/new_ajax_rblock_line'
  match 'rblock_lines/edit_ajax_rblock_line'
  match 'rblock_lines/update_ajax_rblock_line'
  match 'rblock_lines/cancel_ajax_rblock_line'
  match 'rblock_lines/create_ajax_pagebreak'
  match 'rblock_lines/create_ajax_rblock_line'
  match 'rblock_lines/destroy_ajax_rblock_line'
  match 'rblock_lines/order_items'
  match 'rblock_lines/change_scale/:id' => 'rblock_lines#change_scale'
  resources :rblock_lines

  match 'email_attachments/document_choice' => 'email_attachments#document_choice'
  match 'email_attachments/new_document' => 'email_attachments#new_document'
  match 'email_attachments/new_file'
  resources :email_attachments

  match 'contactables/add_document'
  match 'contactables/change'
  match 'contactables/mark_outdated'
  resources :contactables

  match 'addresses/set_delivery_invoice'
  resources :addresses
  resources :email_addresses
  resources :phone_numbers
  resources :people

  match 'customers/rstest'
  match 'customers/search' => 'customers#search'
  match 'customers/add_alias_form' => 'customers#add_alias_form'
  match 'customers/add_contactable_form' => 'customers#add_contactable_form'
  match 'customers/choice_reassign_address/:id(.:format)' => 'customers#choice_reassign_address'
  match 'customers/confirm_reassign_address/:id(.:format)' => 'customers#confirm_reassign_address'
  match 'customers/reassign_address/:id(.:format)' => 'customers#reassign_address'
  match 'customers/select_reassign_existing_contactable' => 'customers#select_reassign_existing_contactable'
  match 'customers/assign_existing_contactable_to_existing_customer/:id(.:format)' => 'customers#assign_existing_contactable_to_existing_customer'
  match 'customers/assign_existingcontactable_to_new_customer' => 'customers#assign_existing_contactable_to_new_customer'
  resources :customers

  resources :users

  root :to => "customers#index"

end

app/models/old_doc.rb
class OldDoc < ActiveRecord::Base
  default_scope order([:customer,:date])

  before_destroy do |od|
    path = File.join(Rails.root, 'public', file_url)
    File.delete path if File.exists? path
  end

  def self.search(search)
    if search
        self.where(['"old_docs"."customer" ilike ?', "%#{search}%"])
    else
      self.scoped
    end
  end
  def prev
    OldDoc.where("(customer = ? AND date < ?) OR customer < ?", customer, date, customer).last
  end
  def next
    OldDoc.where("(customer = ? AND date > ?) OR customer > ?", customer, date, customer).first
  end
  def file_url
    "/old_documents/#{filename}"
  end
end

app/controllers/old_docs_controller.rb
class OldDocsController < ApplicationController
  # GET /old_docs
  # GET /old_docs.json
  def index
    @old_docs = OldDoc.scoped
    @old_docs = @old_docs.search(params[:search]) unless params[:search].blank?
    @old_docs = @old_docs.page(params[:page]).per(50)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @old_docs }
    end
  end

  # GET /old_docs/1
  # GET /old_docs/1.json
  def show
    @old_doc = OldDoc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @old_doc }
    end
  end

  # GET /old_docs/new
  # GET /old_docs/new.json
  def new
    @old_doc = OldDoc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @old_doc }
    end
  end

  # GET /old_docs/1/edit
  def edit
    @old_doc = OldDoc.find(params[:id])
  end

  # POST /old_docs
  # POST /old_docs.json
  def create
    @old_doc = OldDoc.new(params[:old_doc])

    respond_to do |format|
      if @old_doc.save
        format.html { redirect_to @old_doc, notice: 'Old doc was successfully created.' }
        format.json { render json: @old_doc, status: :created, location: @old_doc }
      else
        format.html { render action: "new" }
        format.json { render json: @old_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /old_docs/1
  # PUT /old_docs/1.json
  def update
    @old_doc = OldDoc.find(params[:id])

    respond_to do |format|
      if @old_doc.update_attributes(params[:old_doc])
        # format.html { redirect_to @old_doc, notice: 'Old doc was successfully updated.' }
        flash[:notice] = 'Old doc was successfully updated.'
        format.html { redirect_to :back }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @old_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /old_docs/1
  # DELETE /old_docs/1.json
  def destroy
    @old_doc = OldDoc.find(params[:id])
    @old_doc.destroy

    respond_to do |format|
      flash[:notice] = 'Old doc was destroyed.'
      format.html { redirect_to Rails.application.routes.url_helpers.edit_old_doc_path @old_doc.next }
      # format.html { redirect_to old_docs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/old_docs_helper.rb
module OldDocsHelper
end

app/views/old_docs/_form.html.haml
#prev_next_old_doc
  = link_to 'vorige', edit_old_doc_path(@old_doc.prev) if @old_doc.prev
  = link_to 'nächste', edit_old_doc_path(@old_doc.next) if @old_doc.next
%iframe#old_doc_preview_frame{:src => @old_doc.file_url}
= form_for @old_doc do |f|
  - if @old_doc.errors.any?
    #error_explanation
      %h2= "#{pluralize(@old_doc.errors.count, "error")} prohibited this old_doc from being saved:"
      %ul
        - @old_doc.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :customer
    = f.text_field :customer
  .field
    = f.label :date
    = f.object.date.strftime '%d.%m.%y'
  .field
    = f.label :filename
    = f.object.filename.downcase
  .field
    = f.object.author
  .field
    = f.label :comment
    = f.text_area :comment
  .actions
    = f.submit 'Save'
  = link_to 'löschen', @old_doc, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/old_docs/_old_docs_link.html.haml
- if @open_invoices_count > 0
  = navi_item "#{@open_invoices_count} offene Rechnungen", :controller => :papers, |
    :action => :open_invoices                                                      |

app/views/old_docs/edit.html.haml
%h1 Editing old_doc

%p#notice= notice

= render 'form'

= link_to 'Show', @old_doc
\|
= link_to 'Back', old_docs_path

app/views/old_docs/index.html.haml
%h1 Listing old_docs

= form_tag('old_docs', :method => :get, :id => :old_docs_search, :autocomplete => :off, |
  'data-loading-element' => 'customers_list_container') do                         |
  = text_field_tag :search, params[:search], :autofocus => :autofocus
  = image_submit_tag '/images/micons/b_search.png'
  = image_submit_tag '/images/sweetie/12-em-cross.png', :id => :clear_button
%table
  %tr
    %th Name
    %th Datum
    %th Dateiname
    %th 
    %th
    %th
    %th

  - @old_docs.each do |old_doc|
    %tr
      %td= old_doc.customer
      %td{:title => old_doc.date.strftime('%H:%M')}= old_doc.date.strftime '%d.%m.%y'
      %td= old_doc.filename.downcase
      %td= link_to 'Pdf', old_doc.file_url,                      |
         :target => '_pdf_', :title => 'Pdf', :class => 'pdf icon_link' |
      %td= link_to 'Edit', edit_old_doc_path(old_doc), :class => 'edit icon_link'
      %td= link_to 'Destroy', old_doc, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'delete icon_link'

%br

.pagination
  = paginate @old_docs, :inner_window => 5, :outer_window => 3, :params => {:action => 'index'} 
/ pagination

app/views/old_docs/new.html.haml
%h1 New old_doc

= render 'form'

= link_to 'Back', old_docs_path

app/views/old_docs/show.html.haml
%p#notice= notice

%p
  = @old_doc.customer
%p
  = @old_doc.date
%p
  = @old_doc.filename
%p
  = @old_doc.amount
%p
  = @old_doc.author
%p
  %b Comment:
  = @old_doc.comment

= link_to 'Edit', edit_old_doc_path(@old_doc)
\|
= link_to 'Back', old_docs_path