config/routes.rb
Elephant::Application.routes.draw do
  resources :old_docs

  resources :searches, :only => [:new, :create, :index]

  match 'email_tests/jason'
  resources :email_tests

  match 'cash_books/create_ajax' #=> 'cash_books#create_ajax'
  match 'cash_books/clear'
  resources :cash_books

  match 'authentication/sign_on'
  match 'authentication/login'
  match 'authentication/logout'
  match 'authenticated' => 'authenticated#index'

  match 'documents/preview/:id' => 'documents#preview'
  match 'documents/address_choice/:id' => 'documents#address_choice'
  match 'documents/ajax_choice_linked'
  match 'documents/ajax_destroy_linked'
  match 'documents/ajax_create_linked'
  match 'documents/select_address/:id' => 'documents#select_address'
  match 'documents/destroy_ajax_document'
  resources :documents
  
  resources :document_aliases, :only => [:new, :create]

  match 'emails/unseen_emails' => 'emails#unseen_emails'
  match 'emails/seen/:id' => 'emails#seen'
  match 'emails/destroy_ajax_document'
  resources :emails

  match 'talks/destroy_ajax_document'
  resources :talks
  resources :phone_calls, :controller => :talks
  resources :visits, :controller => :talks

  match 'papers/file/:id(.:format)' => 'papers#file'
  match 'papers/unfile/:id(.:format)' => 'papers#unfile'
  match '/papers/open_invoices'
  match 'papers/change_scale/:id' => 'papers#change_scale'
  match 'papers/ajax_set_state_paid'
  match 'papers/dun_from_invoice'
  match 'papers/invoice_from_offer'
  match 'papers/invoices_from_offer'
  match 'papers/destroy_ajax_document/:id(.:format)' => 'papers#destroy_ajax_document'
  match 'papers/send_by_email/:id' => 'papers#send_by_email'
  resources :papers
  resources :paper_file, :only => [:index, :create, :destroy]

  match 'external_papers/destroy_ajax_document/:id(.:format)' => 'external_papers#destroy_ajax_document'
  match 'external_papers/send_by_email/:id' => 'external_papers#send_by_email'
  resources :external_papers

  match 'contents/new_ajax_content'
  match 'contents/create_ajax_pagebreak'
  match 'contents/create_pagebreak'
  match 'contents/create_ajax_content'
  match 'contents/edit_ajax_content'
  match 'contents/update_ajax_content'
  match 'contents/destroy_ajax_content'
  match 'contents/change_scale/:id' => 'contents#change_scale'
  match 'contents/order_contents'
  match 'contents/order_items'
  match 'contents/cancel_ajax'
  match 'contents/reset_signer'
  resources :contents

  match 'rblock_lines/abschlag'
  match 'rblock_lines/new_ajax_rblock_line'
  match 'rblock_lines/edit_ajax_rblock_line'
  match 'rblock_lines/update_ajax_rblock_line'
  match 'rblock_lines/cancel_ajax_rblock_line'
  match 'rblock_lines/create_ajax_pagebreak'
  match 'rblock_lines/create_ajax_rblock_line'
  match 'rblock_lines/destroy_ajax_rblock_line'
  match 'rblock_lines/order_items'
  match 'rblock_lines/change_scale/:id' => 'rblock_lines#change_scale'
  resources :rblock_lines

  match 'email_attachments/document_choice' => 'email_attachments#document_choice'
  match 'email_attachments/new_document' => 'email_attachments#new_document'
  match 'email_attachments/new_file'
  resources :email_attachments

  match 'contactables/add_document'
  match 'contactables/change'
  match 'contactables/mark_outdated'
  resources :contactables

  match 'addresses/set_delivery_invoice'
  resources :addresses
  resources :email_addresses
  resources :phone_numbers
  resources :people

  match 'customers/rstest'
  match 'customers/search' => 'customers#search'
  match 'customers/add_alias_form' => 'customers#add_alias_form'
  match 'customers/add_contactable_form' => 'customers#add_contactable_form'
  match 'customers/choice_reassign_address/:id(.:format)' => 'customers#choice_reassign_address'
  match 'customers/confirm_reassign_address/:id(.:format)' => 'customers#confirm_reassign_address'
  match 'customers/reassign_address/:id(.:format)' => 'customers#reassign_address'
  match 'customers/select_reassign_existing_contactable' => 'customers#select_reassign_existing_contactable'
  match 'customers/assign_existing_contactable_to_existing_customer/:id(.:format)' => 'customers#assign_existing_contactable_to_existing_customer'
  match 'customers/assign_existingcontactable_to_new_customer' => 'customers#assign_existing_contactable_to_new_customer'
  resources :customers

  resources :users

  root :to => "customers#index"

end

app/models/talk.rb
# coding: utf-8
class Talk < Document
  after_initialize {self.markup = 'markdown' if self.markup.empty? && not(self.persisted?)}

  belongs_to :phone_number, :foreign_key => :address_id
  belongs_to :person, :foreign_key => :address_id

  def main_type
    'Talk'
  end

  def haml_object_ref
    'talk'
  end
end

app/controllers/talks_controller.rb
# coding: utf-8
class TalksController < DocumentsController
end

app/helpers/talk_helper.rb
# coding: utf-8
module TalkHelper
end

app/views/talks/_document_line.html.haml
%li[document]{:class => doc_alias && :document_alias, |
    :data => {'contactable-id' => document.address_id, 'shown-by-lightbulbs-count' => 0, :loaded => (document.too_big? || 'true')}}               |
  .document_line_first{:id => "document_head_#{document.id}"}
    .document_line_icon{:title => document.type}
      %div{:class => "type_icon type_#{document.type.underscore}"}= document.type
      %div{:class => "type_icon type_#{document.is_foreign ? 'in' : 'out'}"}= document.is_foreign ? 'eingehend' : 'ausgehend'
    - if defined?(customer) && customer
      .document_line_customer
        = link_to customer.name, customer
    .document_line_title= document.message_abbr
    .document_line_date{:title => document.date.strftime('%H:%M')}= document.date.strftime '%d.%m.%y'
    .document_line_actions
      -# = link_to 'Anzeigen', document, :class => 'show icon_link', :title => 'Anzeigen'
      = link_to 'Bearbeiten', {:controller => 'talks', :action => 'edit', :id => document}, |
        :class => 'edit icon_link', :title => 'Bearbeiten'                                  |
      -#
      = rs_link_to 'Löschen',                                                                 |
        { :controller => 'documents', :action => 'destroy_ajax_document', :id => document },  |
        'data-loading-element' => "document_#{document.id}",                                  |
        :update => { :failure => "messages" },                                                |
        :confirm => "Wirklich #{document.kind.titlecase} Nr. #{document.id} löschen?",        |
        :class => 'delete icon_link', :title => 'Löschen'                                     |
      = render "document_aliases/actions", :document => document, :doc_alias => doc_alias if doc_alias
  .document_line_second{:id => "document_body_#{document.id}"}
    .document_line_body{:style => "display:none;"}
      = render 'documents/document_line_common', :document => document, :doc_alias => doc_alias
      .document_preview.talk_body{:id => "document_message_#{document.id}", |
              :class => (document.markdown? && ['crevasse_reset','md_preview'])}
        %div{:class => (document.markdown? && ['crevasse_previewer','marked','github_theme']) }
          :preserve
             #{"\n"}#{document.message_formatted unless document.too_big?}

app/views/talks/_form.html.haml
= f.error_messages
%p
  = f.label :date, 'Datum/Uhrzeit'
  %br/
  = f.text_field :date, :class => 'datetimepicker'
%p
  = f.radio_button :is_foreign, true
  = f.label :is_foreign_true, (@document.type == 'PhoneCall' ? 'eingehend' : 'bei uns')
  \&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  = f.radio_button :is_foreign, false
  = f.label :is_foreign_false, (@document.type == 'PhoneCall' ? 'ausgehend' : 'beim Kunden')
.md_area_container
  = f.label :message, 'Inhalt'
  %br/
  = f.text_area :message, :class => 'md_area'
- if f.object.markup == 'markdown'
  .md_preview_container
    &nbsp;
    %br/
    .md_preview
%p.clear
  = f.label :remark, 'Bemerkungen'
  %br
  = f.text_area :remark
%p
  = f.hidden_field :markup
  = f.submit "Speichern"

app/views/talks/_preview.html.haml
.crevasse_previewer.github_theme{:class => (document.markdown? && 'marked') }
  :preserve
    #{"\n"}#{document.message}

app/views/talks/edit.html.haml
%h1= @document.doc_name
%p
  = render "#{@document.contactable.type.to_s.underscore.pluralize}/contactable_line", :contactable => @document.contactable
= render 'documents/linkeds', :document =>  @document
#add_linked
  = rs_link_to 'Verknüpfung hinzufügen',                                                            |
    { :controller => 'documents', :action => 'ajax_choice_linked', :id => @document },              |
    :class => 'icon_link_16 add_linked_16', :title => 'Verknüpfung zu anderem Dokument hinzufügen', |
    'data-loading-element' => 'body'                                                       |
= render 'document_aliases/list', :aliases => @document.aliases, :doc_alias => nil, :skip_rs => true
= form_for(@document) do |f|
  = render 'talks/form', :document => @document, :f => f
= link_to 'Back', @document.customer

app/views/talks/index.html.haml
%h1 Dokumente
%table
  %tr
    %th Id
    %th Kind
    %th Name
    %th Date
    %th Value
  - for document in @documents
    %tr{:title => h(document.remark)}
      %td= document.id
      %td= document.kind.titlecase + ' ' + ( document.invoice_number_formatted || '' )
      %td= h document.name
      %td= h document.date
      %td= h number_to_currency(document.value)
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_document_path(document)
      %td= link_to 'Destroy', document, :confirm => 'Sicher? Das soll man ja eigentlich nicht, ne?', :method => :delete

app/views/talks/new.html.haml
%h1 Neues Gespräch
%p
  = render "#{@document.contactable.type.to_s.underscore.pluralize}/contactable_line", :contactable => @document.contactable
= form_for( @document, :as => @document.type.underscore, :url => { :controller => 'talks', :action => "create", :type => params[:type] }, :html => {:autocomplete => :off}) do |f|
  = render 'talks/form', :document => @document, :f => f
  = f.hidden_field :type
  = f.hidden_field :user_id
  = f.hidden_field :last_modified_by
  = f.hidden_field :address_id
= link_to 'Kunde', @document.customer, :title => 'Zurück zum Kunden'

app/views/talks/show.html.haml
#address_container
  = render 'contactables/contactable_chooser', :document => @document, :contactable => @document.contactable, |
    :show_contactable_chooser => @show_contactable_chooser                                                    |
%p
  %b Datum/Uhrzeit:
  = german_date_time @document.date
%h4
  = "#{@document.kind.titlecase}"
  /= link_to_random( image_tag( 'micons/b_pdfdoc.png', :alt => 'Pdf', :title => 'Pdf' ),  |
  /  {:controller => 'talks', :action => 'show', :format => 'pdf'}, {:target => '_pdf_'}) |
%p
  %b Gespräch:
  = h @document.message
%p
  %b Bemerkung:
  = @document.remark
= render 'documents/document_info', :document => @document
= render 'documents/linkeds', :document => @document
= link_to 'Bearbeiten', edit_talk_path(@document)
|
= link_to 'Kunde', @document.customer