config/routes.rb
Elephant::Application.routes.draw do
  resources :old_docs

  resources :searches, :only => [:new, :create, :index]

  match 'email_tests/jason'
  resources :email_tests

  match 'cash_books/create_ajax' #=> 'cash_books#create_ajax'
  match 'cash_books/clear'
  resources :cash_books

  match 'authentication/sign_on'
  match 'authentication/login'
  match 'authentication/logout'
  match 'authenticated' => 'authenticated#index'

  match 'documents/preview/:id' => 'documents#preview'
  match 'documents/address_choice/:id' => 'documents#address_choice'
  match 'documents/ajax_choice_linked'
  match 'documents/ajax_destroy_linked'
  match 'documents/ajax_create_linked'
  match 'documents/select_address/:id' => 'documents#select_address'
  match 'documents/destroy_ajax_document'
  resources :documents
  
  resources :document_aliases, :only => [:new, :create]

  match 'emails/unseen_emails' => 'emails#unseen_emails'
  match 'emails/seen/:id' => 'emails#seen'
  match 'emails/destroy_ajax_document'
  resources :emails

  match 'talks/destroy_ajax_document'
  resources :talks
  resources :phone_calls, :controller => :talks
  resources :visits, :controller => :talks

  match 'papers/file/:id(.:format)' => 'papers#file'
  match 'papers/unfile/:id(.:format)' => 'papers#unfile'
  match '/papers/open_invoices'
  match 'papers/change_scale/:id' => 'papers#change_scale'
  match 'papers/ajax_set_state_paid'
  match 'papers/dun_from_invoice'
  match 'papers/invoice_from_offer'
  match 'papers/invoices_from_offer'
  match 'papers/destroy_ajax_document/:id(.:format)' => 'papers#destroy_ajax_document'
  match 'papers/send_by_email/:id' => 'papers#send_by_email'
  resources :papers
  resources :paper_file, :only => [:index, :create, :destroy]

  match 'external_papers/destroy_ajax_document/:id(.:format)' => 'external_papers#destroy_ajax_document'
  match 'external_papers/send_by_email/:id' => 'external_papers#send_by_email'
  resources :external_papers

  match 'contents/new_ajax_content'
  match 'contents/create_ajax_pagebreak'
  match 'contents/create_pagebreak'
  match 'contents/create_ajax_content'
  match 'contents/edit_ajax_content'
  match 'contents/update_ajax_content'
  match 'contents/destroy_ajax_content'
  match 'contents/change_scale/:id' => 'contents#change_scale'
  match 'contents/order_contents'
  match 'contents/order_items'
  match 'contents/cancel_ajax'
  match 'contents/reset_signer'
  resources :contents

  match 'rblock_lines/abschlag'
  match 'rblock_lines/new_ajax_rblock_line'
  match 'rblock_lines/edit_ajax_rblock_line'
  match 'rblock_lines/update_ajax_rblock_line'
  match 'rblock_lines/cancel_ajax_rblock_line'
  match 'rblock_lines/create_ajax_pagebreak'
  match 'rblock_lines/create_ajax_rblock_line'
  match 'rblock_lines/destroy_ajax_rblock_line'
  match 'rblock_lines/order_items'
  match 'rblock_lines/change_scale/:id' => 'rblock_lines#change_scale'
  resources :rblock_lines

  match 'email_attachments/document_choice' => 'email_attachments#document_choice'
  match 'email_attachments/new_document' => 'email_attachments#new_document'
  match 'email_attachments/new_file'
  resources :email_attachments

  match 'contactables/add_document'
  match 'contactables/change'
  match 'contactables/mark_outdated'
  resources :contactables

  match 'addresses/set_delivery_invoice'
  resources :addresses
  resources :email_addresses
  resources :phone_numbers
  resources :people

  match 'customers/rstest'
  match 'customers/search' => 'customers#search'
  match 'customers/add_alias_form' => 'customers#add_alias_form'
  match 'customers/add_contactable_form' => 'customers#add_contactable_form'
  match 'customers/choice_reassign_address/:id(.:format)' => 'customers#choice_reassign_address'
  match 'customers/confirm_reassign_address/:id(.:format)' => 'customers#confirm_reassign_address'
  match 'customers/reassign_address/:id(.:format)' => 'customers#reassign_address'
  match 'customers/select_reassign_existing_contactable' => 'customers#select_reassign_existing_contactable'
  match 'customers/assign_existing_contactable_to_existing_customer/:id(.:format)' => 'customers#assign_existing_contactable_to_existing_customer'
  match 'customers/assign_existingcontactable_to_new_customer' => 'customers#assign_existing_contactable_to_new_customer'
  resources :customers

  resources :users

  root :to => "customers#index"

end

app/models/paper.rb
# coding: utf-8
class Paper < Document
  include ToPdf
  include UserInfo
  include ApplicationHelper
  attr_accessible :realization_from, :realization_to, :address_id, :date, :kind, :subject, :remark, :value, :filed
  belongs_to :address, :foreign_key => :address_id
  has_many :contents, :dependent => :destroy, :order => 'position'
  validates_inclusion_of :kind, :in => Elph[:doc_kinds]
  has_one :cash_book, :dependent => :destroy
  # delegate :workshop, :workshop=, :to => :cash_book # just a test
  has_many :email_attachments, :include => {:email => :address}

  scope :invoices, where(:kind => Elph[:inv_kinds]).order('date asc, invoice_number asc')
  scope :unfiled, where(:filed => false, :system => false).order('date asc')
  delegate :rblocks, :to => :contents
  delegate :content_from_template_for_dun, :content_from_template, :invoice_from_estimate, :to => :template
  delegate :update_cash_book, :update_value, :set_invoice_number, :last_invoice_of_year, :to => :invoice_stuff

  after_initialize do
    if new_record? && our_sign.blank? && our_contact.blank?
      u = User.find current_user
      #%w(our_sign our_contact).each {|prop| self.send("#{prop}=",u.send(prop))} # the cryptic way...
      self.our_sign, self.our_contact = u.our_sign, u.our_contact
    end
  end

  before_create do
    set_invoice_number
    self.cash_book = CashBook.new(:date => self.date,
        :tax_rate => self.tax_rate, :amount => 0) if self.kind == 'barrechnung'
  end

  before_update do
    self.value = self.rblocks.first ? self.rblocks.first.total(self.tax_rate) : 0.0 # must pass the (possibly changed) tax_rate explicitly, because it is possibly not up to date
    cash_book.update_attributes({:tax_rate => self.tax_rate,
                  :date => self.date, :amount => self.value }) if cash_book
  end

  def file
    File.open self.pdf_local_path, 'wb' do |fh|
      fh.write self.to_pdf
    end
    self.update_attribute :filed, true
  end

  def unfile
    self.update_attribute :filed, false
  end

  def pdf_url
    self.filed ? URI.encode("/filed_papers/#{self.pdf_name}") : "/papers/#{self.id}.pdf"
  end

  def file_url # provisorium
    pdf_url
  end

  def foile_name # provisorium
    pdf_name
  end

  def to_blob # same same
    filed ? File.read(pdf_local_path) : self.to_pdf(:chop => Elph[:mail_papers_with_chop])
  end

  def pdf_name
   "#{self.kind.titlecase} #{'%05d' % self.id}.pdf"
  end

  def pdf_local_path
    "#{Rails.root.to_s}/public/filed_papers/#{self.pdf_name}"
  end

  def rft_both?
    return false if realization_from.nil?
    realization_from < realization_to
  end

  def template
    @template ||= PaperTemplate.new self
  end

  def invoice_stuff
    @invoice_stuff ||= InvoiceStuff.new self
  end

  def dun_times?
    Elph[:inv_states].index(self.state)
  end

  def value_formatted
    number_to_currency value
  end

  #validates_with_block do
  #	self.realization_from > self.realization_to ? true : [ false,  '\'vom\' darf nicht größer als \'bis\' sein' ]
  #end

  def based_ons
    Paper.find :all, :conditions => "based_on=#{self.id}"
  end
end

app/controllers/papers_controller.rb
# coding: utf-8
            
class PapersController < DocumentsController

  include ActionView::Helpers::NumberHelper # for eval in content_from_template
  include PapersHelper


  # GET /documents
  # GET /documents.xml
  def index
    #subset = {:limit => @customers_per_page.to_i, :offset => @customers_per_page.to_i * session[:page].to_i, :order => 'name'}
    subset = {:order => 'date desc, id desc'}
    #subset[:conditions] = [ 'name like ?', "#{session[:limit_to_char]}%" ] unless session[:limit_to_char] == 'all'
    @papers = Paper.find(:all, subset)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @papers }
    end
  end

  # GET /papers/1
  # GET /papers/1.xml
  def show
    @paper = Paper.find(params[:id])
    @show_contactable_chooser = @paper.contactable.customer.addresses.length > 1
    
    respond_to do |format|
      if @paper.filed?
        format.html { redirect_to "#{@paper.file_url}", :status => 302 }
        format.pdf { redirect_to "#{@paper.file_url}", :status => 302 }
      else
        format.html # show.html.erb
        format.xml  { render :xml => @paper }
        format.pdf do
          pdf = @paper.to_pdf(:chop => params[:chop])
          Rails.taciturn_logger.info pdf.size
          send_data pdf, :type => 'application/pdf', :disposition => 'inline', :filename => @paper.doc_name
        end
      end
    end
  end

  # GET /papers/new
  # GET /papers/new.xml
  def new
    @paper = Paper.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @paper }
    end
  end

  # GET /papers/1/edit
  def edit
    @paper = Paper.find(params[:id])
    @users = User.find(:all)
  end

  # POST /papers
  # POST /papers.xml
  def create
    @paper = Paper.new(params[:paper])

    @paper.transaction do
      respond_to do |format|
        if @paper.save
          flash[:notice] = 'Document was created.'
          @paper.content_from_template
          format.html { redirect_to(@paper) }
          format.xml  { render :xml => @paper, :status => :created, :location => @paper }
        else
          @document = @paper
          format.html { render :action => "new" }
          format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /papers/1
  # PUT /papers/1.xml
  def update
    @paper = Paper.find(params[:id])
    
    respond_to do |format|
      if @paper.update_attributes(params[:paper])
        flash[:notice] = 'Document was successfully updated.'
        format.html { redirect_to(@paper) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @paper.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /papers/1
  # DELETE /papers/1.xml
  def destroy
    @paper = Paper.find(params[:id])
    #@paper.destroy
    flash[:notice] = 'Geht nicht, weil nicht gut...'

    respond_to do |format|
      format.html { redirect_to(papers_url) }
      format.xml  { head :ok }
    end
  end

  def file
    @paper = Paper.find(params[:id])
    @paper.file
    respond_to do |format|
      format.jsonrs
    end
  end

  def unfile
    @paper = Paper.find(params[:id])
    @paper.unfile
  end

  def send_by_email_old
    paper = Paper.find(params[:id])

    @document = Email.new :address_id => paper.customer.current_email_addresses[0].id, :subject => "#{paper.kind.titlecase} #{paper.invoice_number_formatted || paper.id}"
    @document.attachments << EmailAttachment.new( { :kind => 'paper', :paper_id => paper.id } )
    @document.set_user_info session[:user]
    
    render :template => 'emails/new'
  end

  def destroy_ajax_document

    @document = Paper.find(params[:id])

    if Elph[:inv_kinds].include? @document.kind 
      i_number = InvoiceNumber.find :first, :conditions => { :year =>  @document.date.year }
      if @document.invoice_number == i_number.number
        Paper.transaction do
          i_number.update_attribute :number, i_number.number - 1
          @document.destroy
        end
        render :template => 'documents/destroy_ajax_document'
      else
        #l_o_year = Paper.find :first, :conditions => "YEAR(date)='#{i_number.year.to_s}' AND invoice_number='#{i_number.number}'", :include => :address
        l_o_year = Paper.find :first, :conditions => "date_part('year',date)='#{i_number.year.to_s}' AND invoice_number='#{i_number.number}'", :include => :address
        part_two = l_o_year ? "\n\nDie letzte Rechnung ist die #{l_o_year.kind.titlecase} Nr. #{l_o_year.invoice_number_formatted}\n"\
                                + "    (Dok._Nr. #{l_o_year.id}) an '#{l_o_year.address.name}'." \
                            : ''
        render :template => 'common/alert', :locals => { :message => "Es kann immer nur die letzte Rechnung gelöscht werden."\
                            +	 part_two }
      end
    else
      @document.destroy
      render :template => 'documents/destroy_ajax_document'
    end
  end
  
  def change_scale
    @paper = Paper.find(params[:id])
    if @paper.update_attribute :scale, params[:value]
      render :nothing => true
    else
      render :nothing => true, :status => 404
    end
  end
  
  def open_invoices
    @papers = Paper.open_invoices
    #@total = @documents.inject(0.0) {|sum,d| sum + d.value.to_f}
    @total = @papers.sum(:value).to_f

    tct_logger.info DocumentAlias.class.to_s

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @papers }
    end
  end

  def ajax_set_state_paid
    @paper = Paper.find(params[:id])
    if @paper
      @paper.update_attribute :state, 'paid'
      @new_total = Paper.open_invoices.sum(:value)
      render :template => 'papers/set_state_paid'
    end
  end
  
  def dun_from_invoice
    @odoc = Paper.find(params[:id])
    @paper = Paper.new :kind => 'mahnung', :address_id => @odoc.address_id, :date => Time.now, :based_on => @odoc.id
    @nth_dun = @odoc.dun_times? + 1
    if @paper.save
      fire_log "@paper.id = '#{@paper.id}'"
      flash[:notice] = 'Document was created.'
      @paper.content_from_template_for_dun @odoc
      @odoc.update_attribute :state, Elph[:inv_states][@nth_dun]
      @odoc.linkees << @paper
      redirect_to(@paper)
    else
      flash[:notice] = 'kacke!'
      fire_log @paper.errors.full_messages
      render :text => @paper.errors.full_messages
      redirect_to('open_invoices')
    end 
  end

  def invoices_from_offer
    @paper = Paper.find(params[:id])
  end
  
  def invoice_from_offer
    @odoc = Paper.find(params[:id])
    if @odoc.based_ons.length > 0 && ! params[:force]
      redirect_to :action => 'invoices_from_offer', :id => @odoc.id  and return
    end
    @paper = Paper.new :kind => 'rechnung', :address_id => @odoc.address_id, :date => Time.now, :based_on => @odoc.id, :value => @odoc.value, :realization_to => Date.today, :realization_from => Date.today
    @paper.set_user_info session[:user]
    if @paper.save
      @paper.invoice_from_estimate @odoc
      @odoc.linkees << @paper
      redirect_to(@paper) and return
    else
      fire_log @paper.errors.full_messages
      render :text => @paper.errors.full_messages and return
    end
  end
  
  protected
end

app/helpers/papers_helper.rb
# coding: utf-8

module PapersHelper
  include Prawn::Measurements
  include ElphConfig
  include ActionView::Helpers::NumberHelper
  
  def address_lines c
    al = []
    l23 = [ quote_amp(c.line2), quote_amp(c.line3) ]
    l23.each {|l| al << ' ' if l.nil? || l.empty? }
    al << quote_amp(c.full_name)
    l23.each {|l| al << l unless l.nil? || l.empty? }
    al << "#{c.street} #{c.number}" << "#{c.zip} #{c.city}" << c.country
  end
  
  def quote_amp str
    # str.gsub /&(?![\w#]+;)/,'&amp;' if str
    str   # somtimes we need it, sometimes not...
  end
end

app/views/papers/_document_line.html.haml
%li[document]{:class => doc_alias && :document_alias, 'data-contactable-id' => document.address_id, |
    'data-shown-by-lightbulbs-count' => 0}  |
  .document_line_first{:id => "document_head_#{document.id}"}
    .document_line_icon{:title => document.class.model_name.human}
      %div{:class => "type_icon type_#{document.type.underscore}"}= document.type
      .type_icon.type_none weder noch
    - if defined?(customer) && customer
      .document_line_customer
        = link_to customer.name, customer
    .document_line_title
      %span.paper_title{:title => document.id}
        = "#{document.kind.titlecase} #{document.invoice_number_formatted || document.id}"
      %span.paper_subject{:title => document.subject}= document.subject_abbr 30
    .document_line_date{:title => document.date.strftime('%H:%M')}= document.date.strftime '%d.%m.%y'
    / <div align="right"><haml:loud> number_to_currency(document.value) </haml:loud></div>
    .document_line_actions
      - unless document.filed
        = link_to 'Bearbeiten', {:controller => 'papers', :action => 'show',   |
          :id => document}, :class => 'edit icon_link', :title => 'Bearbeiten' |
        -#
        = link_to 'Metadaten bearbeiten', {:controller => 'papers', :action => 'edit',   |
          :id => document}, :class => 'edit icon_link', :title => 'Metadaten bearbeiten' |
        -#
        = rs_link_to 'Archivieren',                                         |
          { :controller => 'papers', :action => 'file', :id => document },  |
          'data-loading-element' => "paper_#{document.id}",                     |
          :class => 'file icon_link', :title => 'Archivieren'               |
        -#
        = rs_link_to 'Löschen',                                                                                                  |
          { :controller => 'papers', :action => 'destroy_ajax_document', :id => document },                 |
          'data-loading-element' => :customers_preview,                         |
          :confirm => "Wirklich #{document.kind.titlecase} Nr. #{document.invoice_number_formatted || document.id} löschen?", |
          :class => 'delete icon_link', :title => 'Löschen'                                                                   |
        -#
      - unless document.remark.blank?
        %a.icon_link.info{"data-toggle-sometimes-hidden" => "paper_remark_#{document.id}", :href => "#"} info ein-/ausblenden
      = link_to_random 'Pdf', document.pdf_url, :target => '_pdf_', :title => 'Pdf', :class => 'pdf icon_link'
      -#
      = rs_link_to 'bearbeitbar',                                         |
        { :controller => 'papers', :action => 'unfile', :id => document },  'data-loading-element' => "paper_#{document.id}",  |
          :class => 'unfile icon_link', :title => 'wieder bearbeitbar machen',                                            |
          :confirm => 'Das Dokument wirklich wieder bearbeitbar machen?' if document.filed |
      -#
      = link_to_random 'Pdf mit Stempel', {:controller => 'papers', :action => 'show', :id => document, |
        :format => 'pdf', :chop => 'chop'}, :target => '_pdf_', :title => 'Pdf mit Stempel',            |
        :class => 'pdf icon_link' unless document.filed                                                 |
      -#
      = link_to( '€',                                                                                                                                            |
        { :controller => 'papers', :action => 'invoice_from_offer', :id => document },                                                                           |
        :title => "Rechnung auf Basis dieses #{document.kind.titlecase}es erstellen",                                                                            |
        :confirm => "Wirklich eine Rechnung auf Basis dieses #{document.kind.titlecase}es erstellen?") if ['kostenvoranschlag','angebot'].include? document.kind |
      -#
      = link_to( 'Versenden', {:controller => 'papers', :action => 'send_by_email', :id => document,                                             |
        :type => 'Email'}, {:class => 'send icon_link', :title => 'Per Email versenden'}) if document.customer.current_email_addresses.count > 0 |
      -#
      = render "document_aliases/actions", :document => document, :doc_alias => doc_alias if doc_alias
  - unless document.remark.blank?
    %div.remark.hide_sometimes_hidden{:id=>"paper_remark_#{document.id}"}
      %p.sometimes_hidden
        = document.remark
  .document_line_second{:id => "document_body_#{document.id}"}
    .document_line_body{:style => "display:none;"}
      = render 'documents/document_line_common', :document => document, :doc_alias => doc_alias
      .document_preview.paper_body{:id => "document_message_#{document.id}"}
      / gonna be replaced by ajax

app/views/papers/_open_invoices.html.haml
%table
  %thead
    %tr
      %th Id
      %th Nummer
      %th Name
      %th Datum
      %th Summe
  %tfoot
    %tr
      %td
      %td
      %td
      %td Insges.
      %td#open_invoices_total= number_to_currency(@total)
  %tbody
    - for document in @papers
      %tr{:class => "invoice_state_#{document.state}", :id => "open_invoices_#{document.id}", :title => document.remark}
        %td{:style => "text-align:right;"}= document.id
        %td= document.invoice_number_formatted || ''
        %td= link_to h(document.address.name), document.customer
        %td{:style => "text-align:center;"}= h german_date(document.date)
        %td{:style => "text-align:right;"}= h number_to_currency(document.value)
        %td{:id => "state_label_#{document.id}"}= Elph[:inv_state_labels][document.state.to_sym]
        %td= link_to 'Show', document, :class => 'edit icon_link', :title => 'anzeigen'
        %td= link_to 'Edit', edit_paper_path(document), :class => 'edit icon_link', :title => 'bearbeiten'
        %td.change_state_link
          = rs_link_to 'Bezahlt',                                                                               |
            { :action => 'ajax_set_state_paid', :id => document, :state => 'paid'},                             |
            :confirm => "Wirklich Rechnung Nr. #{document.invoice_number_formatted} als bezahlt kennzeichnen?", |
            :class => 'set_paid icon_link', :title => 'als bezahlt kennzeichnen'                                |
        %td.change_state_link
          = link_to 'Mahnen', {:action => 'dun_from_invoice', :id => document},                             |
            :class => 'make_dun icon_link', :title => 'Mahnung erstellen',                                  |
            :confirm => "Wirklich Mahnung für Rechnung Nr. #{document.invoice_number_formatted} erstellen?" |

app/views/papers/_open_invoices_link.html.haml
- if @open_invoices_count > 0
  = navi_item "#{@open_invoices_count} offene Rechnungen", :controller => :papers, |
    :action => :open_invoices                                                      |

app/views/papers/_ref_fields.html.haml
#ref_fields
  .inline
    = f.label :your_message
    %br
    = f.text_field :your_message
  .inline
    = f.label :your_sign
    %br
    = f.text_field :your_sign
  .inline
    = f.label :our_sign
    %br
    = f.text_field :our_sign
  %div
    = f.label :our_contact
    = f.text_area :our_contact

app/views/papers/index.html.haml
%h1 Dokumente
%table
  %tr
    %th Id
    %th Kind
    %th Name
    %th Date
    %th Value
  - for document in @papers
    %tr{:title => document.remark}
      %td= document.id
      %td= document.kind.titlecase + ' ' + ( document.invoice_number_formatted || '' )
      %td= document.address.name
      %td= german_date document.date
      %td= number_to_currency(document.value)
      %td= link_to 'Show', document
      %td= link_to 'Edit', edit_paper_path(document)
      / <td><haml:loud> link_to 'Destroy', document, :confirm =&amp;gt; 'Sicher? Das soll man ja eigentlich nicht, ne?', :method =&amp;gt; :delete </haml:loud></td>

app/views/papers/invoices_from_offer.html.haml
Es existieren bereits folgende auf #{@paper.kind.titlecase} #{@paper.id} basierende Dokumente:
%table
  %thead
    %tr
      %th Id
      %th Nummer
      %th Name
      %th Datum
      %th Summe
  %tfoot
    %tr
      %td
      %td
      %td
      %td Insges.
      %td= number_to_currency(@total)
  %tbody
    - for document in @paper.based_ons
      %tr{:class => "invoice_state_#{h document.state}", :id => "open_invoices_#{document.id}", :title => document.remark}
        %td{:style => "text-align:right;"}= document.id
        %td= document.invoice_number_formatted || ''
        %td= h document.address.name
        %td{:style => "text-align:center;"}= h german_date(document.date)
        %td{:style => "text-align:right;"}= h number_to_currency(document.value)
        %td{:id => "state_label_#{document.id}"}= Elph[:inv_state_labels][document.state.to_sym]
        %td= link_to 'Show', document
        %td= link_to 'Edit', edit_paper_path(document)
%p
  = link_to 'Trotzdem eine neue Rechnung erstellen',                                          |
    { :controller => 'papers', :action => 'invoice_from_offer', :id => @paper, :force => 1 }, |
    :title => "Rechnung auf Basis dieses #{@paper.kind.titlecase}es erstellen"                |

app/views/papers/open_invoices.html.haml
%h1 Offene Rechnungen
= render :partial => 'papers/open_invoices'

app/views/papers/show.html.haml
- content_for :js_declarations do
  = "var rblock_line_form = \"#{escape_javascript(render('rblock_lines/new_rblock_line', :content_id => 'CONTENT_ID'))}\"".html_safe;
.scroller
  #contactable_container
    = render :partial => 'contactables/contactable_chooser', :locals => { :document => @paper,     |
      :contactable => @paper.contactable, :show_contactable_chooser => @show_contactable_chooser } |
  %p
    %b Datum:
    = german_date @paper.date
  %p
    %b Betreff:
    = @paper.subject
  %h4
    = "#{@paper.kind.titlecase} #{@paper.invoice_number_formatted || @paper.id}"
    = link_to_random( 'Pdf', {:controller => 'papers', :action => 'show', :format => 'pdf'}, |
         {:target => '_pdf_', :title => 'Pdf', :class => 'icon_link pdf'}) |
    -#
    = link_to_random('Pdf', {:controller => 'papers', :action => 'show', :format => 'pdf', :chop => 'chop'}, |
         {:target => '_pdf_', :title => 'Pdf mit Stempel', :class => 'icon_link pdf'}) |
    -#
  -# .scale_slider{:id => "paper_#{@paper.id}_scale_slider", 'data-value' => @paper.scale}
  %table#paper_contents
    %tbody#contents_list{'data-sortable-controller' => 'contents', 'data-sortable-handle' => '.cl_handle'}
      / contents_list verflucht!
      - unless @paper.contents.empty?
        - for content in @paper.contents
          = render "contents/#{content.kind}", :content => content
      - else
        = render "contents/first_content", :paper_id => @paper.id
  /= sortable_element("contents_list", :url => { :controller => 'contents', :action => "order_contents" }, |
    :tag => 'tr', :handle => 'cl_handle')                                                                 |
  %hr{:style => "margin-top:40px;"}
  = render 'documents/linkeds', :document =>  @paper
  = render 'document_aliases/list', :aliases => @paper.aliases, :doc_alias => nil, :skip_rs => true
  %p
    %b Bemerkungen:
    = h @paper.remark
  %p.doc_info
    %b Erzeugt von:
    = h "#{@paper.user.gname} #{@paper.user.name}"
    = german_date_time @paper.created_at
    %b Zuletzt bearbeitet von:
    = h "#{@paper.modifier.gname} #{@paper.modifier.name}"
    = german_date_time @paper.updated_at
- content_for :footer do
  .footer_cont
    = link_to 'Bearbeiten', edit_paper_path(@paper)
    |
    = link_to 'Kunde', @paper.address.customer
    - if ['kostenvoranschlag','angebot'].include? @paper.kind
      | #{link_to 'Rechnung erstellen',  { :controller => 'papers', :action => 'invoice_from_offer', :id => @paper },  :title => "Rechnung auf Basis dieses #{@paper.kind.titlecase}es erstellen"}