config/routes.rb
Elephant::Application.routes.draw do
  resources :old_docs

  resources :searches, :only => [:new, :create, :index]

  match 'email_tests/jason'
  resources :email_tests

  match 'cash_books/create_ajax' #=> 'cash_books#create_ajax'
  match 'cash_books/clear'
  resources :cash_books

  match 'authentication/sign_on'
  match 'authentication/login'
  match 'authentication/logout'
  match 'authenticated' => 'authenticated#index'

  match 'documents/preview/:id' => 'documents#preview'
  match 'documents/address_choice/:id' => 'documents#address_choice'
  match 'documents/ajax_choice_linked'
  match 'documents/ajax_destroy_linked'
  match 'documents/ajax_create_linked'
  match 'documents/select_address/:id' => 'documents#select_address'
  match 'documents/destroy_ajax_document'
  resources :documents
  
  resources :document_aliases, :only => [:new, :create]

  match 'emails/unseen_emails' => 'emails#unseen_emails'
  match 'emails/seen/:id' => 'emails#seen'
  match 'emails/destroy_ajax_document'
  resources :emails

  match 'talks/destroy_ajax_document'
  resources :talks
  resources :phone_calls, :controller => :talks
  resources :visits, :controller => :talks

  match 'papers/file/:id(.:format)' => 'papers#file'
  match 'papers/unfile/:id(.:format)' => 'papers#unfile'
  match '/papers/open_invoices'
  match 'papers/change_scale/:id' => 'papers#change_scale'
  match 'papers/ajax_set_state_paid'
  match 'papers/dun_from_invoice'
  match 'papers/invoice_from_offer'
  match 'papers/invoices_from_offer'
  match 'papers/destroy_ajax_document/:id(.:format)' => 'papers#destroy_ajax_document'
  match 'papers/send_by_email/:id' => 'papers#send_by_email'
  resources :papers
  resources :paper_file, :only => [:index, :create, :destroy]

  match 'external_papers/destroy_ajax_document/:id(.:format)' => 'external_papers#destroy_ajax_document'
  match 'external_papers/send_by_email/:id' => 'external_papers#send_by_email'
  resources :external_papers

  match 'contents/new_ajax_content'
  match 'contents/create_ajax_pagebreak'
  match 'contents/create_pagebreak'
  match 'contents/create_ajax_content'
  match 'contents/edit_ajax_content'
  match 'contents/update_ajax_content'
  match 'contents/destroy_ajax_content'
  match 'contents/change_scale/:id' => 'contents#change_scale'
  match 'contents/order_contents'
  match 'contents/order_items'
  match 'contents/cancel_ajax'
  match 'contents/reset_signer'
  resources :contents

  match 'rblock_lines/abschlag'
  match 'rblock_lines/new_ajax_rblock_line'
  match 'rblock_lines/edit_ajax_rblock_line'
  match 'rblock_lines/update_ajax_rblock_line'
  match 'rblock_lines/cancel_ajax_rblock_line'
  match 'rblock_lines/create_ajax_pagebreak'
  match 'rblock_lines/create_ajax_rblock_line'
  match 'rblock_lines/destroy_ajax_rblock_line'
  match 'rblock_lines/order_items'
  match 'rblock_lines/change_scale/:id' => 'rblock_lines#change_scale'
  resources :rblock_lines

  match 'email_attachments/document_choice' => 'email_attachments#document_choice'
  match 'email_attachments/new_document' => 'email_attachments#new_document'
  match 'email_attachments/new_file'
  resources :email_attachments

  match 'contactables/add_document'
  match 'contactables/change'
  match 'contactables/mark_outdated'
  resources :contactables

  match 'addresses/set_delivery_invoice'
  resources :addresses
  resources :email_addresses
  resources :phone_numbers
  resources :people

  match 'customers/rstest'
  match 'customers/search' => 'customers#search'
  match 'customers/add_alias_form' => 'customers#add_alias_form'
  match 'customers/add_contactable_form' => 'customers#add_contactable_form'
  match 'customers/choice_reassign_address/:id(.:format)' => 'customers#choice_reassign_address'
  match 'customers/confirm_reassign_address/:id(.:format)' => 'customers#confirm_reassign_address'
  match 'customers/reassign_address/:id(.:format)' => 'customers#reassign_address'
  match 'customers/select_reassign_existing_contactable' => 'customers#select_reassign_existing_contactable'
  match 'customers/assign_existing_contactable_to_existing_customer/:id(.:format)' => 'customers#assign_existing_contactable_to_existing_customer'
  match 'customers/assign_existingcontactable_to_new_customer' => 'customers#assign_existing_contactable_to_new_customer'
  resources :customers

  resources :users

  root :to => "customers#index"

end

app/models/search.rb
class Search
  attr_accessor :customers, :contactables, :documents

  def initialize(params)
    if params.include? 'search_pns'
      results = phone_number_search(params['search_adv'], params['search_pns_full'])
      @contactables = Contactable.where(id: results.map(&:phone_number_id).uniq)
      @customers = Customer.where(id: @contactables.map(&:customer_id).uniq)
    end
  end
  
  def phone_number_search(pn, full)
    PhoneNumberSpecific.search(pn, full)
  end
  
  def sphinx_search(s_str, models)
    
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include CustomersPagination

  def index
    @search = Search.new(params)
    @search.customers = @search.customers.page(params[:page]).per(_customers_per_page) if @search.customers

    respond_to do |format|
      format.jsonrs # index.jsonrs.jrs
      format.html # index.html.erb
      format.xml  { render :xml => @searches }
    end
  end

  def new
    @search = Search.new

    respond_to do |format|
      format.jsonrs
      format.html # new.html.erb
      format.xml  { render :xml => @search }
    end
  end

  # POST /searches
  def create
    @search = Search.new(params)
    @search.customers = @search.customers.page(params[:page]).per(_customers_per_page)

    respond_to do |format|
      format.jsonrs { render :action => "index" }
      format.html { render :action => "index" }
      format.xml  { render :xml => @searches}
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.haml
= rs_form_tag('searches', :method => :get, :id => :searches_form, :autocomplete => :off, |
              'data-loading-element' => 'customers_list_container') do                   |
  = text_field_tag :search_adv, params[:search_adv], :autofocus => :autofocus
  = image_submit_tag '/images/micons/b_search.png'
  = image_submit_tag '/images/sweetie/12-em-cross.png', :id => :clear_button
  %span.search_pns_full{:style => params[:search_pns] || 'display: none;'}
    = check_box_tag :search_pns_full, nil, params[:search_pns_full], :class => :search_pns_cb_full
    = label_tag :search_pns_full, 'ganze Nummer'
  .search_options
    %span
      = check_box_tag :search_customers, nil, params[:search_customers], :class => 'search_model'
      = label_tag :search_customers, 'Kontakte'
    %span
      = check_box_tag :search_documents, nil, params[:search_documents], :class => 'search_model'
      = label_tag :search_documents, 'Dokumente'
    %span
      = check_box_tag :search_pns, nil, params[:search_pns], :class => :search_pns_cb
      = label_tag :search_pns, 'Telefonnummern'

app/views/searches/edit.html.haml
%h1 Editing search

= render 'form'

= link_to 'Show', @search
\|
= link_to 'Back', searches_path

app/views/searches/index.html.haml
%h1 Listing searches

%table
  %tr
    %th Search
    %th Model
    %th
    %th

    %tr
      %td search.search
      %td search.model
      %td link_to 'Show', search
      %td link_to 'Edit', edit_search_path(search)

%br

= link_to 'New Search', new_search_path

app/views/searches/new.html.haml
%h1 New search

= render 'form'

= link_to 'Back', searches_path

app/views/searches/show.html.haml
%p#notice= notice

%p
  %b Search:
  = @search.search
%p
  %b Model:
  = @search.model

= link_to 'Edit', edit_search_path(@search)
\|
= link_to 'Back', searches_path